[project]
name = "phospho-docking"
version = "0.1.0"
description = "In silico phosphopeptide docking pipeline using AutoDock Vina"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "meeko",
    "vina",
    "rdkit",
    "biopython",
    "openbabel-wheel",
    "pandas",
    "matplotlib",
    "jinja2",
    "scipy>=1.17.1",
    "numpy>=2.4.3",
    "gemmi>=0.7.5",
]

[project.scripts]
phospho-dock = "phospho_docking.cli:main"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]
